### PR TITLE
fix: missing rooms on existing friendships

### LINKED ISSUE #39: Fix for missing friendships
Currently existing friendships in server are identified, but cannot be found later while running the tests.

### PR DESCRIPTION
**Pull request by moliva**
Fixes #39 .

- Adds room id to user state when friendship is already available
- Panics when user act has no room, as this is a precondition
- Panics if the room selected to be used cannot be retrieved from client
- Ignores local users JSON files
- Adds `launch.json` for VS Code debugger with sample configuration
- Deriving `Debug` for `User` and `Synching`
- Minor change to logging
- Minor refactors
- Minor change to example config TOML doc
- Adds basic test to validate example config file attributes

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -87,3 +100,25 @@ async fn create_users(config: Configuration) {
...
+            homeserver: "home".to_owned(),
+            output_dir: "output".to_owned(),
+            create: true,
+            delete: false,
+            run: false,
+            amount: 42,
+            users_filename: "users".to_owned(),
+        };
+
+        parse_configuration("Config.example", args)?;
```
Comment (guidota) [inline src/main.rs:120]: Is `Config.example` correct? (without `.toml`)

**Review by guidota — APPROVED** [review]
LGTM :+1:
